feat(ci): create setup-oe action
sportsball-ai/actions-hub pull request #6
Opened 2022-06-17 21:40 UTC by jonathankao97

2022-06-21 18:51 UTC, beiriannydd requested changes
I really like the idea of this, it is actually a fairly general case "setup go" action.  Maybe we should call it that instead of setup-oe.  I really want us to make sure we keep our documentation up to date.  Is there any way that we can have tests for actions?

2022-06-21 18:51 UTC, beiriannydd commented on setup-oe/action.yml
> +        echo password ${{  inputs.password }} >> ~/.netrc
is there any way to make sure that these are secrets?
is there documentation?

2022-06-21 20:05 UTC, jonathankao97 commented on setup-oe/action.yml
> +        echo password ${{  inputs.password }} >> ~/.netrc
All workflow runs still occur in the environment where the composite action is used. If they are stored as a secret in that workflow, they will be treated as a secret throughout

2022-06-21 20:07 UTC, jonathankao97 commented
@beiriannydd i see what you mean by this action being a generic setup-go action. Should consumers of this action first pull setup-go and then manually run go install with the correct endpoint?

2022-06-28 16:13 UTC, raven-txm requested changes

2022-06-28 16:13 UTC, raven-txm commented on setup-nexus-go/action.yml
> +        echo machine ${{ inputs.endpoint }} >> ~/.netrc
Instead of being multiple lines of echo, can we just use a bash heredoc?
https://mywiki.wooledge.org/HereDocument

2022-06-29 17:26 UTC, raven-txm approved these changes

2022-06-29 18:08 UTC, merged